package WarstwaAplikacji;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MenuGlowneAdmin {
    private JLabel menuLabel;
    public JPanel menuAdminFrame;
    private JButton modyfikujDaneKontaButton;
    private JButton usuńKontoButton;
    private JButton dodajPolączenieButton;
    private JButton modyfikujPołączenieButton;
    private JButton usuńPołączenieButton;
    public static JFrame frameDodajPolaczenie;
    public static JFrame frameModyfikujPolaczenie;
    public static JFrame frameUsunPolaczenie;

    public MenuGlowneAdmin() {
        modyfikujDaneKontaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                JFrame frameModyfikujKonto = new JFrame("Modyfikowanie Danych Konta");
                frameModyfikujKonto.setContentPane(new ModyfikacjaDanychKonta().modyfikacjaKontaFrame);
                frameModyfikujKonto.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frameModyfikujKonto.pack();
                frameModyfikujKonto.setVisible(true);
            }
        });
        usuńKontoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                JFrame frameUsunKonto = new JFrame("Usuwanie Konta");
                frameUsunKonto.setContentPane(new UsuwanieKonta().usuwanieKontaFrame);
                frameUsunKonto.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frameUsunKonto.pack();
                frameUsunKonto.setVisible(true);
            }
        });
        dodajPolączenieButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                frameDodajPolaczenie = new JFrame("Dodawanie Połączenia");
                frameDodajPolaczenie.setContentPane(new DodawaniePolaczenia().dodawaniePolaczeniaFrame);
                frameDodajPolaczenie.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frameDodajPolaczenie.pack();
                frameDodajPolaczenie.setVisible(true);
            }
        });
        modyfikujPołączenieButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                frameModyfikujPolaczenie = new JFrame("Modyfikowanie Połączenia");
                frameModyfikujPolaczenie.setContentPane(new ModyfikacjaPolaczenia().modyfikacjaPolaczeniaFrame);
                frameModyfikujPolaczenie.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frameModyfikujPolaczenie.pack();
                frameModyfikujPolaczenie.setVisible(true);
            }
        });
        usuńPołączenieButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                frameUsunPolaczenie = new JFrame("Usuwanie Połączenia");
                frameUsunPolaczenie.setContentPane(new UsuwaniePolaczenia().usuwaniePolaczeniaFrame);
                frameUsunPolaczenie.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                frameUsunPolaczenie.pack();
                frameUsunPolaczenie.setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        menuAdminFrame = new JPanel();
        menuAdminFrame.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        menuLabel = new JLabel();
        menuLabel.setText("Menu Główne");
        menuAdminFrame.add(menuLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modyfikujDaneKontaButton = new JButton();
        modyfikujDaneKontaButton.setText("Modyfikuj Dane Konta");
        menuAdminFrame.add(modyfikujDaneKontaButton, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(126, 30), null, 0, false));
        dodajPolączenieButton = new JButton();
        dodajPolączenieButton.setText("Dodaj Polączenie");
        menuAdminFrame.add(dodajPolączenieButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(126, 30), null, 0, false));
        modyfikujPołączenieButton = new JButton();
        modyfikujPołączenieButton.setText("Modyfikuj Połączenie");
        menuAdminFrame.add(modyfikujPołączenieButton, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(181, 30), null, 0, false));
        usuńPołączenieButton = new JButton();
        usuńPołączenieButton.setText("Usuń Połączenie");
        menuAdminFrame.add(usuńPołączenieButton, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(167, 30), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        menuAdminFrame.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        menuAdminFrame.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(9, 11), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        menuAdminFrame.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(2, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        menuAdminFrame.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(9, 11), null, 0, false));
        usuńKontoButton = new JButton();
        usuńKontoButton.setText("Usuń Konto");
        menuAdminFrame.add(usuńKontoButton, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(167, 30), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return menuAdminFrame;
    }

}
